# Events

## Get all events

GET http://localhost:8080/events

###

## Get event by id

GET http://localhost:8080/events/153aee0e-6761-4ee6-8655-6c76bc9a96fd

###

## Create event

POST http://localhost:8080/events
Content-Type: application/json

{
    "title": "Event 1",
    "description": "Description 1",
    "date": "2024-11-17",
    "image": "https://blog.hubspot.de/hubfs/Germany/Blog_images/Optimize_Marketing%20Events%20DACH%202021.jpg"
}

###

## Update event

PATCH http://localhost:8080/events/153aee0e-6761-4ee6-8655-6c76bc9a96fd
Content-Type: application/json

{
    "title": "The dummy event",
    "description": "Join this amazing event and connect with fellow developers.",
    "date": "2024-11-17",
    "image": "https://blog.hubspot.de/hubfs/Germany/Blog_images/Optimize_Marketing%20Events%20DACH%202021.jpg"
}

###

## Delete event

DELETE http://localhost:8080/events/dc4225f5-5754-4e02-80c1-9

###